apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-flask-app
  namespace: ns-flask-app
spec:
  rules:
    - host: app-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nginx-dev
                port:
                  number: 80
