apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - flask-deployment.yaml
  - flask-service.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - ingress.yaml

configMapGenerator:
  - name: cm-nginx
